
name: Ben Scott
url: http://bescott.org/
avatar: "/rsc/ben-rules.jpg"
github_username: evan-erdos
description: "2016-03-16: I'm the Supreme Fascist of the CMU Computer Club!"

footer-links:
  email: bescott@andrew.cmu.edu
  github: evan-erdos
  #facebook: IASJazz
  #youtube: channel/UCGAciiuP89ERn-iqUuYHFBQ
  #rss: rss
  #linkedin: /404
  #twitter: /404
  stackoverflow: users/5266983/ben-scott
  #dribbble:
incremental: true
#google_analytics:
disqus:
baseurl: ""

#markdown: kramdown
#math_engine: mathjax

#kramdown:
#  input: GFM
#  syntax_highlighter_ops:

#highlighter: pygments
permalink: /:title/
version: v1.9.2

#stylus:
#  compress: true
#  path: ./path/to

sass:
  style: :compressed # ! :expanded

gems:
- jekyll-sitemap
#- jekyll-redirect-from

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
