# This file contains configuration flags
name: Ben Scott
url: http://bescott.org/
avatar: "/rsc/ben-rules.jpg"
github_username: evan-erdos
description: "2015-10-24: Wow, look, it's Three.js WebGL right now!"
footer-links:
  email: bescott@andrew.cmu.edu
  github: evan-erdos
  facebook: IASJazz
  #youtube: channel/UCGAciiuP89ERn-iqUuYHFBQ
  #rss: rss
  #linkedin: /404
  #twitter: /404
  stackoverflow: users/5266983/ben-scott
  #dribbble:
#google_analytics:
disqus:
baseurl: ""
markdown: redcarpet
redcarpet:
  extensions:
  - no_intra_emphasis
  - fenced_code_blocks
  - autolink
  - tables
  - with_toc_data
  - strikethrough
  - footnotes
  - highlight
  - superscript

#kramdown:
#  input: GFM
#  syntax_highlighter: coderay
#  coderay_css: 'fruity.css'

highlighter: pygments
permalink: /:title/
version: v1.9.2

#stylus:
#  compress: true
#  path: ./path/to

sass:
  style: :compressed # ! :expanded

gems:
- jekyll-sitemap

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
