
name: Ben Scott
url: http://bescott.org/
avatar: "/rsc/ben-rules.jpg"
github_username: evan-erdos
description: |
  v1.0.5-beta: replaced all deprecated "reality" dependencies
  with virtual reality spaceships

footer-links:
  email: bescott@andrew.cmu.edu
  github: evan-erdos
  #facebook: IASJazz
  #youtube: channel/UCGAciiuP89ERn-iqUuYHFBQ
  #rss: rss
  #linkedin: /404
  #twitter: /404
  stackoverflow: users/5266983/ben-scott
  #dribbble:
#incremental: true
#google_analytics:
disqus:
baseurl: ""

kramdown:
  input: GFM

#highlighter: pygments

permalink: /:title/
version: v1.9.2

#stylus:
#  compress: true
#  path: ./path/to

sass:
  style: :compressed # ! :expanded

gems:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-coffeescript

whitelist:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-coffeescript

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
